name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npx cypress run

      - name: Upload report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: /home/runner/work/cypress-cucumber-automation/cypress-cucumber-automation/cypress/reports/html